version: '3.4'

services:
  app:
    depends_on:
        - worker
    restart: always
    build:
      dockerfile: Dockerfile.app
      context: ./app
    image: joao/alqueva:latest
    container_name: alqueva_app
    user: root
    ports:
      - 49162:8080
    environment:
      - NODE_ENV: "${NODE_ENV}"
      - PORT: "${APP_PORT}"
      - REDIS_URL: "${REDIS_URL}"
      - NODE_API: "${NODE_API}"
      - REACT_APP_NODE_API: "${REACT_APP_NODE_API}"
      - REACT_APP_CI_COMMIT_TAG: "${REACT_APP_CI_COMMIT_TAG}"
    networks:
        - alquevanet
  
  worker:
    depends_on:
      - redis
      - influx-db
    restart: always
    build:
      dockerfile: Dockerfile.worker
      context: ./worker
    image: joao/alqueva_worker:latest
    container_name: alqueva_worker
    environment:
      - NODE_ENV: "${NODE_ENV}"
      - PORT: "${WK_PORT}"
      - REDIS_URL: "${REDIS_URL}"
      - DATABASE_URL: "${DATABASE_URL}"
      - INFLUXDB_TOKEN: "${INFLUXDB_TOKEN}"
      - INFLUXDB_ORG: "${INFLUXDB_ORG}"
      - INFLUXDB_BUCKET: "${INFLUXDB_BUCKET}"
      - FIRST_URL: "${FIRST_URL}"
      - SECOND_URL: "${SECOND_URL}"
    networks:
        - alquevanet

  redis:
    image: redis:latest
    depends_on:
      - influx-db
    container_name: alqueva_redis
    restart: unless-stopped
    volumes:
      - redisdata
    networks:
      - alquevanet

  influx-db:
    image: influxdb:latest
    container_name: alqueva_influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE: "${DOCKER_INFLUXDB_INIT_MODE}"
      - DOCKER_INFLUXDB_INIT_USERNAME: "${DOCKER_INFLUXDB_INIT_USERNAME}"
      - DOCKER_INFLUXDB_INIT_PASSWORD: "${DOCKER_INFLUXDB_INIT_PASSWORD}"
      - DOCKER_INFLUXDB_INIT_ORG: "${DOCKER_INFLUXDB_INIT_ORG}"
      - DOCKER_INFLUXDB_INIT_BUCKET: "${DOCKER_INFLUXDB_INIT_BUCKET}"
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}"
    volumes:
      - dbdata1:/var/lib/influxdb2
      - dbdata2:/etc/influxdb2
    networks:
      - alquevanet

volumes:
  redisdata:
  dbdata1:
  dbdata2:

networks:
  alquevanet:
    driver: bridge